name: Weather Analysis Task

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 20 * * *'
    workflow_dispatch: # Allows you to run it manually for testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Weather Script
      env:
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      run: python weather_script.py